import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BottomNav from "@/components/mui-bottom-nav";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <AppRouterCacheProvider options={{ enableCssLayer: true }}>
      <html lang="en">
        <body className={inter.className}>
          {children}{" "}
          <div className="fixed bottom-0 left-0 right-0">
            <BottomNav />
          </div>
        </body>
      </html>
    </AppRouterCacheProvider>
  );
}
